version: "3"

services:
    redis:
        image: redis:5
        ports:
            - "6379"
    
    
    # nginx:
    #     image: nginx
    #     ports:
    #         - "3000:3000"
    #         # - "443:443"
    #     volumes:
    #         - ./nginx.conf:/etc/nginx/nginx.conf
    #         - /etc/nginx/proxy_params:/etc/nginx/proxy_params
    #         - ./static:/home/slaven92/draganKviz/dragan/static/
    #     depends_on: 
    #         - web

    web:
        build: .
        ports: 
            - "8000:8000"
        volumes:
            - .:/dragan/
        depends_on: 
            - db
            - redis
        # entrypoint: ["gunicorn", "-b", "0.0.0.0:8000", "-w","2", "--access-logfile", "-" , "-k", "uvicorn.workers.UvicornWorker", "dragan.asgi:application"]
        entrypoint: ["python", "/dragan/manage.py", "runserver", "0.0.0.0:8000"]


    db:
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432"
    
    memcached:
        image: memcached
        ports: 
            - "11211"