query data {
  allQuestions {
    edges {
      node {
        id
        questionText
        voteCount
        userDidVote
        creator{
          username
        }
        choiceSet {
          edges {
            node {
              id
              choiceText
              votes
            }
          }
        }
      }
    }
  }
}
